# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "megaraid_sas" "usbhid" "usb_storage" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/bd6a0869-9097-4f16-b57d-a9b350ab7d46";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  fileSystems."/mnt/btr_pool" =
    { device = "/dev/disk/by-uuid/bd6a0869-9097-4f16-b57d-a9b350ab7d46";
      fsType = "btrfs";
      options = [ "subvolid=5" ];
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/bd6a0869-9097-4f16-b57d-a9b350ab7d46";
      fsType = "btrfs";
      options = [ "subvol=var" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/bd6a0869-9097-4f16-b57d-a9b350ab7d46";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E997-B128";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp7s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
