- name: Play
  hosts: all
  gather_subset:
    - devices
    - distribution
    - kernel
    - mounts
  become: true
  vars:
    baptize_method: softreboot
    image_url: https://tunnel.backyard-hg.net/image/root.raw.zst

    stop_cloud_init: true
    stop_apt: true
  tasks:
    - name: Terminate cloud-init
      ansible.builtin.service:
        name: "{{ item }}"
        state: stopped
      when: stop_cloud_init
      failed_when: false
      loop:
        - cloud-init
        - cloud-init-local
        - cloud-final

    - name: Terminate apt
      when: >-
        ansible_facts["distribution"] in ["Debian", "Ubuntu"] and
        stop_apt
      block:
        - name: Terminate apt process
          ansible.builtin.shell:
            cmd: |-
              set -ex
              procs="$(pgrep 'apt' || echo '')"
              [ -z "$procs" ] && exit 0
              echo "killing $procs"
              kill -TERM $procs
          register: terminate
          changed_when: "'killing' in terminate.stdout"
          timeout: 300

        - name: Restore dpkg database
          # noqa: no-handler
          ansible.builtin.shell:
            cmd: |-
              dpkg --configure -a
              apt-get install -f -y
          retries: 15
          delay: 8
          until: >-
            restore is not failed or
            (restore.stdout is not search("lock") and
            restore.stderr is not search("lock"))
          register: restore
          when: terminate is changed
          changed_when: true

    - name: Set target disk
      when: target_disk is undefined
      block:
        - name: Find device mounted at root
          ansible.builtin.set_fact:
            root_partition: >-
              {{
                (ansible_facts["mounts"]
                  | selectattr('mount', 'equalto', '/')
                  | list
                  | first
                ).device | basename
              }}

        - name: Find parent disk
          ansible.builtin.set_fact:
            target_disk: "/dev/{{ item.key }}"
          loop: "{{ ansible_facts['devices'] | dict2items }}"
          when:
            - item.value.partitions is defined
            - root_partition in item.value.partitions.keys() | list

    # TODO: add method auto, try softreboot then kexec

    - name: Run kexec installer
      ansible.builtin.include_role:
        name: baptize_kexec
      when: baptize_method == "kexec"

    - name: Run soft-reboot installer
      ansible.builtin.include_role:
        name: baptize_softreboot
      when: baptize_method == "softreboot"

    - name: Wait for port 22
      ansible.builtin.wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        delay: 100
        sleep: 10
        timeout: 1200
      delegate_to: localhost
      become: false
